/**sELECT STATEMENT*/
SELECT AC_NUMBER, CHAR_DESTINATION FROM CHARTER;

SELECT * FROM EMPLOYEE;

/*SELECT DISTINCT statement*/
SELECT DISTINCT AC_NUMBER, CHAR_DESTINATION from CHARTER;

/**WHERE CLAUSE*/
SELECT * FROM EMPLOYEE
WHERE EMP_TITLE = 'Mr.';

SELECT * FROM EMPLOYEE
WHERE EMP_NUM = 102;

SELECT * FROM EMPLOYEE WHERE EMP_INITIAL = '';

UPDATE EMPLOYEE
SET EMP_INITIAL = 'V'
WHERE EMP_NUM = 102;

/** ORDER BY */

SELECT * FROM EMPLOYEE
ORDER BY EMP_HIRE_DATE;

SELECT EMP_NUM, EMP_HIRE_DATE
FROM EMPLOYEE
ORDER BY EMP_NUM, EMP_HIRE_DATE ASC;

SELECT * FROM EMPLOYEE
ORDER BY EMP_NUM DESC;

SELECT * FROM CUSTOMER
ORDER BY CUS_FNAME ASC;

SELECT * FROM CUSTOMER
ORDER BY CUS_FNAME ASC, CUS_BALANCE DESC;


/**sql AND Operator */

SELECT * FROM EMPLOYEE
WHERE EMP_NUM = 100 AND EMP_FNAME like 'C%';

SELECT * FROM EMPLOYEE
WHERE EMP_NUM = 100 
AND EMP_INITIAL = 'T'
AND EMP_TITLE = 'Mr.';

SELECT * FROM AIRCRAFT
WHERE MOD_CODE = 'PA31-350'
AND AC_NUMBER = '2778V'
AND AC_TTAF = 7992.9;

UPDATE AIRCRAFT
SET AC_TTEL = 1513.1
WHERE AC_NUMBER = '4278Y'
AND AC_TTER = 243.2;

SELECT * FROM AIRCRAFT
WHERE MOD_CODE = 'PA31-350'
AND AC_TTEL = 1513.1
OR AC_TTER = 243.2; 

SELECT * FROM CHARTER
WHERE CHAR_DESTINATION LIKE 'ATL%'
OR CUS_CODE = 10011
OR CHAR_OIL_QTS = 1;

SELECT * FROM CHARTER
WHERE CHAR_DESTINATION LIKE 'A%'
AND CHAR_DESTINATION = 'ATL'
OR CHAR_OIL_QTS = 1;

/** COMBINING AND and OR */
SELECT * FROM CHARTER
WHERE CUS_CODE = 10011
AND CHAR_DESTINATION LIKE 'ATL'
OR CHAR_TRIP = 10001;


/**The NOT Operator*/
SELECT * FROM CHARTER
WHERE NOT CHAR_DESTINATION = 'ATL';

/**NOT LIKE */
SELECT * FROM CHARTER
WHERE CHAR_TRIP NOT LIKE 10002;

SELECT * FROM CHARTER
WHERE CHAR_DESTINATION NOT LIKE 'A%';

/**NOT BETWEEN AND */
SELECT * FROM CHARTER 
WHERE CHAR_TRIP NOT BETWEEN 10013 AND 10016;

/**NOT GREATER THAN */
SELECT * FROM EMPLOYEE
WHERE NOT EMP_NUM > 101;

/**NOT LESSER THAN*/
SELECT CHAR_TRIP, AC_NUMBER, CHAR_DESTINATION FROM CHARTER
WHERE NOT CHAR_TRIP < 10009;

/**INSERT INTO */
select * from RATING;
insert into RATING (RTG_CODE, RTG_NAME)
values ('SET', 'Single Engine. Town, Land');

INSERT INTO RATING 
VALUES ('SAT', 'Single Action .Town, Land');

insert into RATING (RTG_CODE)
values ('CCT');

UPDATE RATING
SET RTG_NAME = null
WHERE RTG_CODE = 'CCT';

UPDATE RATING 
SET RTG_NAME = 'COPORATE COPER TOWN'
WHERE RTG_CODE = 'CCT';


/**IS NULL OPERATOR*/

/**SELECT * FROM EMPLOYEE
WHERE 
*/

UPDATE EMPLOYEE
SET EMP_INITIAL = NULL
WHERE EMP_NUM = 100;

SELECT * FROM EMPLOYEE 
WHERE EMP_NUM = 100;

